template_function: _.template

javascripts:
  app:
    - public/javascripts/vendor/jquery-1.5.min.js
    - public/javascripts/vendor/underscore-1.1.4.min.js
    - public/javascripts/vendor/backbone-0.3.3.min.js
    - public/javascripts/vendor/backbone.rails.js
    - public/javascripts/rails.js
    - public/javascripts/application.js
    - public/javascripts/vendor/jquery.dotimeout.js
    - public/javascripts/models/**/*.js
    - public/javascripts/collections/**/*.js
    - public/javascripts/controllers/**/*.js
    - public/javascripts/views/**/*.js
    - app/views/**/*.jst
